Repository voxpupuli/beaker-rspec, pull requests merged in 2023-03, with the labels that each got.

#118 Introduce rubocop
  .github/dependabot.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .rubocop.yml
  .rubocop_todo.yml
  Rakefile
  beaker-rspec.gemspec
Labels: enhancement

#121 Drop Ruby 2.4/2.5/2.6
  .github/workflows/test.yml
  .rubocop.yml
  .rubocop_todo.yml
  beaker-rspec.gemspec
Labels: backwards-incompatible

#117 Support uppercase configuration environment variables
  lib/beaker-rspec/spec_helper.rb
Labels: enhancement

#120 Add Ruby 3.2 support
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: enhancement

#126 Release 8.0.0
  CHANGELOG.md
  lib/beaker-rspec/version.rb
Labels: skip-changelog
